# Generated by Django 5.1 on 2024-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='candidate_images')),
                ('goals', models.TextField()),
                ('party_name', models.CharField(max_length=100)),
                ('party_logo', models.ImageField(upload_to='party_logo')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='service_images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('voter_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('voter_password', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='voter_images')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('citizenship_front', models.ImageField(unique=True, upload_to='=citizenship_front')),
                ('citizenship_back', models.ImageField(unique=True, upload_to='citizenship_back')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
